### ISSUE TITLE
Freezes on Windows, Node.js >=v10.2

### ISSUE THREAD

**Issue by KSR-Yasuda** [cezaraugusto/mklicense#2]
On Windows environment and Node >=v10.2,
it freezes after the message `generating license`.

* Does Not Work on
    * Windows 8.1 Pro (x64)
        * Node.js: >=v10.2.0 (Checked as NG on v10.2.0, v10.2.1, v10.5.0, v10.9.0, v10.10.0, v10.15.3, v12.3.1)
* Works on
    * Windows 8.1 Pro (x64)
        * Node.js: <v10.2.0 (Checked as OK on v10.1.0, v10.0.0, v9.11.2, v8.16.0)
    * Ubuntu 14.04.6 LTS (x64)
        * Node.js: ANY (Checked as OK on v10.15.3, v8.16.0)

It looks `jsdom.env()` is not responding.

While it is working on Ubuntu,
some change at Node.js v10.2 would have made something wrong on `jsdom`, just on Windows.

It would be `jsdom`'s problem, probably,
but it would have better rewrite the `jsdom.env()` call
while `jsdom.env()` has gone until `jsdom` latest v15.1.0.

**Comment by KSR-Yasuda** [comment]
At last, it appeared to be **`inquirer`'s problem**, actually.

Updating `inquirer` v1.0.2 -> v6.3.1 (latest), it goes (on Win 8.1 Pro x64, node v10.15.3).

```diff
diff --git a/package.json b/package.json
index 603d955..06a58e2 100644
--- a/package.json
+++ b/package.json
@@ -39,7 +39,7 @@
   "dependencies": {
     "cli-spinner": "^0.2.5",
     "git-user-name": "^1.2.0",
-    "inquirer": "^1.0.2",
+    "inquirer": "^6.3.1",
     "jsdom": "^8.5.0"
   },
   "devDependencies": {
```

**Comment by KSR-Yasuda** [comment]
`inquirer` v3.0.6 (NG or Freeze) <=> v3.1.0 (OK) is the border.

**Comment by cezaraugusto** [comment]
fixed by https://github.com/cezaraugusto/mklicense/pull/3

**Comment by KSR-Yasuda** [comment]
Thank you for the merging! :)
